### ISSUE TITLE
Need access to data

### ISSUE THREAD

**Issue by Manas-Embold** [CC2Vec/CC2Vec#2]
Hi,
Thanks for sharing the Implementation of awesome work.

Can you provide access to dataset, its currently restricted.
I would be thankful for the same.

Also, it would be great if you can explain how can we create our own dataset or the preprocessing steps, in case provided data is already processed. 
Mail id for access: man.shukla101@gmail.com

**Comment by CC2Vec** [comment]
Dear Manas, 

Many thanks for your interest in our paper. It seems that there are some problems with google drive. Please use the link below to download the datasets and pre-trained models.

https://zenodo.org/record/3965149#.X2VeP5MzY1J
I don't have time to explain the preprocessing steps for now since I'm a bit busy. I'll do in the future. 

Thank you and have a great day.
